services:
  # 프론트엔드 서버
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mission-clean-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - mission-clean-network

networks:
  mission-clean-network:
    driver: bridge 