# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies, including devDependencies
RUN npm install && npm cache clean --force

# Copy the rest of the application code
COPY . .

# Expose port
EXPOSE 3001

# Start the server with nodemon for hot-reloading
CMD ["npm", "run", "dev"] 